// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Blog.Entities;
using Microsoft.EntityFrameworkCore;

namespace Blog.Entities
{
    [Table(nameof(PostImage))]
    public class PostImage
    {
        public Guid Id { get; set; }

        [Column(TypeName = "varchar(max)")]
        public string Path { get; set; }

        [ForeignKey(nameof(Post))]
        public Guid PostId { get; set; }

        public Post Post { get; set; }
    }
}