// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Blog.Models;

[Table(nameof(ImageLink))]
public class ImageLink
{
    public Guid Id { get; set; }

    [StringLength(256)]
    [Column(TypeName = "nvarchar")]
    public string Name { get; set; }

    [ForeignKey(nameof(Post))]
    public Guid PostId { get; set; }

    [Column(TypeName = "varchar(max)")]
    public string Link { get; set; }

    public Post Post { get; set; }
}