// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Blog.Models;

public partial class Image
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public int? BlogId { get; set; }

    [Unicode(false)]
    public string Link { get; set; }

    [ForeignKey("BlogId")]
    [InverseProperty("Images")]
    public virtual Post Blog { get; set; }
}