// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Blog.Models;

public partial class Post
{
    [Key]
    public int Id { get; set; }

    [StringLength(450)]
    public string AuthorId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Slug { get; set; }

    [StringLength(256)]
    public string Title { get; set; }

    public string Description { get; set; }

    public int? CategoryId { get; set; }

    public string Content { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Posts")]
    public virtual Category Category { get; set; }

    [InverseProperty("Blog")]
    public virtual ICollection<Image> Images { get; set; } = new List<Image>();
}